version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx", "|", "grep", "works"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
